---
title: "Mendota_totalP_external"
author: "Lauren A. Knose, ORISE-EPA"
date: '2023-05-30'
output: html_document
---

The purpose of this program is to calculate the combined total P input to Lake 
Mendota from external sources (three main inflows and atmospheric deposition).

# Step 1. Load the packages and data needed...

```{r}
library(dplyr) #needed for transforming data
library(lubridate) #needed for date conversion functions
library(ggplot2) #needed for plotting
```

Packages loaded.

```{r}
Inflows_sumP<- read.csv(file="Cleaned_data/Mendota_P_inflows.csv")
Inflows<- Inflows_sumP %>%
  mutate(X.1=NULL, #remove erroneous columns
         X = NULL) %>%#remove erroneous columns
  mutate(sampledate=as.Date(sampledate, origin="1899-12-30")) %>%
  filter(year(sampledate) >=2012 & year(sampledate) <= 2022)

AtmP<- read.csv(file="Cleaned_data/Mendota_P_atm.csv")
AtmP<- AtmP %>%
  mutate(X=NULL, #remove erroneous columns
         sampledate=as.Date(SampleDate, origin="1899-12-30")) #convert to date
```

Data loaded.

# Step 2. Combine the data:

```{r}
TotP_external<- merge(Inflows, AtmP, #merge two data frames
                all=TRUE) #keep all records for both data frames
TotP_external %>%
  
```
